COMP2007-S2016-Lesson10C/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using COMP2007_S2016_Lesson10C.Models;

namespace COMP2007_S2016_Lesson10C.Controllers
{
/*
 * Author: Robert Page 200281838
 * Website: http://robcomp2007assignment2.azurewebsites.net/
 * Description: this displays the menu views
*/
    public class MenuController : Controller
    {

        MenuContext storeDB = new MenuContext();

        //
        // GET: /Menu/
        public ActionResult Index()
        {


            List<Album> food = storeDB.Albums.ToList();
            return View(food);

        }
        //
        // GET: /Menu/Browse?genre=Disco

        public ActionResult Browse(string genre = "Rock")
        {
            // Retrieve Genre and its Associated Albums from database
            Genre genreModel = storeDB.Genres.Include("Albums").Single(g => g.Name == genre);

            return View(genreModel);
        }
        //
        // GET: /Menu/Details/5

        public ActionResult Details(int id = 1)
        {
            Album album = storeDB.Albums.Find(id);

            return View(album);
        }
    }
}

COMP2007-S2016-Lesson10C/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using COMP2007_S2016_Lesson10C.Models;

namespace COMP2007_S2016_Lesson10C.Controllers
{
    public class StoreManagerController : Controller
    {
/*
 * Author: Robert Page 200281838
 * Website: http://robcomp2007assignment2.azurewebsites.net/
 * Description: this shoud not do anything but has been left incase of unexpected errors
*/
        private MusicStoreContext db = new MusicStoreContext();

        // GET: StoreManager
        public ActionResult Index()
        {
            var albums = db.Albums.Include(a => a.Artist).Include(a => a.Genre);
            return View(albums.ToList());
        }

        // GET: StoreManager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // GET: StoreManager/Create
        public ActionResult Create()
        {
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name");
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name");
            return View();
        }

        // POST: StoreManager/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Albums.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            return View(album);
        }

        // GET: StoreManager/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            return View(album);
        }

        // POST: StoreManager/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", album.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", album.GenreId);
            return View(album);
        }

        // GET: StoreManager/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: StoreManager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Album album = db.Albums.Find(id);
            db.Albums.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

COMP2007-S2016-Lesson10C/Views/Menu/Browse.cshtml
@using COMP2007_S2016_Lesson10C.Models
@model Genre

@{
    ViewBag.Title = "Browse";
}
@*
    Author: Robert Page 200281838
    Website: http://robcomp2007assignment2.azurewebsites.net/
    Description: this file used to do something but has had its functonality moved
                however like with other files had issues being removed
*@
<h2>Browsing Menu: @Model.Name</h2>

<ul>
    @foreach (Album album in Model.Albums)
    {
        <li>
            @Html.ActionLink(album.Title,"Details", new { id = album.AlbumId })
        </li>
    }
</ul>

COMP2007-S2016-Lesson10C/Views/Menu/Details.cshtml
@using COMP2007_S2016_Lesson10C.Models
@model Album
@*
    Author: Robert Page 200281838
    Website: http://robcomp2007assignment2.azurewebsites.net/
    Description: this file shows the user the food in greater detail
*@
@{
    ViewBag.Title = "Details";
}

<h2>@Model.Genre.Name: @Model.Title</h2>

        <img src="@Model.AlbumArtUrl" alt="@Model.Title" />

<h1>Price: $@Model.Price</h1>
    

<p>
    <a href="@Url.Action("../Menu")" class="btn btn-default" title="Menu"><i class="fa fa-book"></i> Return To The Menu</a>
</p>
@*<a href="@Url.Action("Edit","StoreManager", new { id = Model.AlbumId })" class="btn btn-default"><i class="fa fa-pencil"></i> Edit</a>*@

COMP2007-S2016-Lesson10C/Views/Menu/Index.cshtml
@using COMP2007_S2016_Lesson10C.Models
@model IEnumerable<Album>
@*
    Author: Robert Page 200281838
    Website: http://robcomp2007assignment2.azurewebsites.net/
    Description: this file shows the list of mood to the user
*@
@{
    ViewBag.Title = "Index";

}
<h1>Menu</h1>

<ul>

    @foreach (Album album in Model)
    {

        <li>
            <h2>@album.Genre.Name</h2>
            <a href="@Url.Action("Details","Menu",  new { id = album.AlbumId })"> <img src="@album.AlbumThumbUrl" alt="@album.Title" /> <br /> @album.Title</a>
        </li>
    }

</ul>